// <auto-generated />
using System;
using Elomoas.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Elomoas.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Elomoas.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IdentityId")
                        .HasColumnType("text");

                    b.Property<string>("Img")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Elomoas.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Img")
                        .HasColumnType("text");

                    b.Property<string>("Learn")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PL")
                        .HasColumnType("integer");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Video")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Embark on a comprehensive journey into Python data science excellence. Master the fundamentals of Python for data analysis and manipulation. Dive deep into pandas, numpy, and scikit-learn libraries. Learn to build powerful machine learning models using Python. Understand data visualization techniques with matplotlib and seaborn. Explore advanced statistical analysis methods with Python. Master data cleaning and preprocessing techniques. Complete the course with real-world data science projects.",
                            Img = "/images/v-1.png",
                            Learn = "Master Python for data science^Build machine learning models^Handle large datasets^Create data visualizations^Implement statistical analysis^Clean and preprocess data^Deploy machine learning models^Build data pipelines",
                            Name = "Python Data Science Mastery",
                            PL = 6,
                            Price = 240,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Become an expert in Java development with comprehensive training. Master core Java concepts and object-oriented programming principles. Learn enterprise patterns and architectures for scalable applications. Develop robust applications using Spring Framework and Spring Boot. Understand microservices architecture and implementation with Java. Master database integration and ORM frameworks like Hibernate. Learn testing strategies and continuous integration practices. Implement security best practices in Java applications.",
                            Img = "/images/v-2.png",
                            Learn = "Master Java fundamentals^Build enterprise applications^Implement Spring Framework^Create microservices^Handle database operations^Secure Java applications^Deploy enterprise systems^Implement testing strategies",
                            Name = "Modern Java Development",
                            PL = 5,
                            Price = 280,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Transform into a professional React developer with comprehensive training. Master component-based architecture and React hooks for modern applications. Learn state management patterns with Redux and Context API. Implement responsive and accessible user interfaces with React. Explore advanced React patterns and performance optimization techniques. Build full-stack applications with React and popular backend technologies. Master testing methodologies for React applications. Deploy and scale React applications in production environments.",
                            Img = "/images/v-3.png",
                            Learn = "Build modern React applications^Master Redux state management^Create responsive user interfaces^Implement React hooks effectively^Test React components^Optimize application performance^Handle authentication and routing^Deploy React applications",
                            Name = "React and Redux Professional",
                            PL = 4,
                            Price = 200,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Master MongoDB database development and administration. Learn to design efficient and scalable database schemas. Understand MongoDB query optimization and indexing strategies. Implement data modeling patterns for different use cases. Master aggregation framework for complex data analysis. Learn database security and access control in MongoDB. Understand backup, restoration, and disaster recovery procedures. Deploy and manage MongoDB in production environments.",
                            Img = "/images/v-4.jpg",
                            Learn = "Design database schemas^Optimize MongoDB queries^Implement data modeling^Use aggregation framework^Secure MongoDB databases^Handle backup and recovery^Monitor database performance^Deploy MongoDB clusters",
                            Name = "MongoDB Database Engineering",
                            PL = 7,
                            Price = 220,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Master modern web development with HTML5 from the ground up. Learn semantic HTML5 elements and modern page structure techniques. Explore advanced features including Web Components and Custom Elements. Implement responsive design patterns for mobile-first development. Master form handling and validation techniques in HTML5. Learn accessibility best practices for inclusive web development. Understand modern SEO techniques and best practices. Create beautiful and functional web interfaces with HTML5.",
                            Img = "/images/v-5.jpg",
                            Learn = "Create semantic HTML5 markup^Build responsive layouts^Implement Web Components^Handle forms and validation^Ensure web accessibility^Optimize for SEO^Create modern interfaces^Deploy web applications",
                            Name = "HTML5 and Modern Web",
                            PL = 1,
                            Price = 150,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Master the latest version of Bootstrap framework for modern web development. Learn to create responsive and mobile-first websites with Bootstrap 5. Understand the Bootstrap grid system and flexible layout components. Implement modern UI components and interactive elements with Bootstrap. Master customization techniques and theme creation with Sass. Learn best practices for responsive web design with Bootstrap. Explore advanced Bootstrap features and plugins for enhanced functionality. Build professional websites with Bootstrap's comprehensive toolkit.",
                            Img = "/images/v-6.jpg",
                            Learn = "Master Bootstrap 5 fundamentals^Create responsive layouts^Implement UI components^Customize with Sass^Build mobile-first websites^Use Bootstrap plugins^Optimize performance^Deploy Bootstrap projects",
                            Name = "Bootstrap 5 Framework Mastery",
                            PL = 0,
                            Price = 160,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Master jQuery for modern web development and DOM manipulation. Learn advanced event handling and custom event creation. Understand jQuery animation and effects for interactive interfaces. Implement AJAX and asynchronous data handling with jQuery. Master plugin development and extension creation. Learn performance optimization techniques for jQuery applications. Understand jQuery security best practices and validation. Build professional web applications with jQuery.",
                            Img = "/images/v-7.jpg",
                            Learn = "Master jQuery fundamentals^Handle events effectively^Create custom animations^Implement AJAX calls^Develop jQuery plugins^Optimize performance^Secure applications^Build interactive interfaces",
                            Name = "Advanced jQuery Development",
                            PL = 2,
                            Price = 170,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Master modern CSS development with Sass preprocessor. Learn advanced Sass features including mixins and functions. Understand modular CSS architecture with Sass. Implement responsive design patterns using Sass capabilities. Master CSS organization and maintenance with Sass. Learn best practices for scalable stylesheet development. Explore advanced Sass features for complex styling needs. Build maintainable and efficient stylesheets with Sass.",
                            Img = "/images/v-8.jpg",
                            Learn = "Master Sass fundamentals^Create reusable mixins^Build modular stylesheets^Implement responsive design^Organize CSS architecture^Optimize stylesheets^Use advanced Sass features^Deploy optimized CSS",
                            Name = "Sass and Modern CSS",
                            PL = 3,
                            Price = 140,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Master web development using Python and Django framework. Learn to build scalable web applications with Django's powerful features. Understand MTV architecture and Django's core components. Implement authentication, authorization, and user management systems. Master database operations and ORM usage in Django. Learn REST API development with Django REST framework. Understand testing and debugging in Django applications. Deploy Django applications to production environments.",
                            Img = "/images/v-9.jpg",
                            Learn = "Build Django applications^Create REST APIs^Handle authentication^Manage databases^Test Django apps^Deploy web services^Optimize performance^Implement security",
                            Name = "Python Web Development with Django",
                            PL = 6,
                            Price = 210,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Learn game development fundamentals using Java and popular gaming frameworks. Master core concepts of game programming and design patterns. Understand game physics and collision detection implementation. Create engaging user interfaces and game mechanics. Learn sound and graphics programming in Java. Master game state management and scene transitions. Implement multiplayer functionality and networking. Deploy and publish Java games across platforms.",
                            Img = "/images/v-10.jpg",
                            Learn = "Create Java games^Implement game physics^Handle user input^Manage game states^Add sound and graphics^Create multiplayer features^Optimize game performance^Deploy games",
                            Name = "Java Game Development",
                            PL = 5,
                            Price = 250,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Master mobile app development with React Native framework. Learn to build cross-platform mobile applications efficiently. Understand native component integration and mobile-specific features. Implement responsive and adaptive mobile user interfaces. Master state management in mobile applications. Learn offline data storage and synchronization. Understand mobile app testing and debugging strategies. Deploy applications to iOS and Android platforms.",
                            Img = "/images/v-1.png",
                            Learn = "Build mobile apps^Create native UIs^Handle device features^Manage app state^Implement offline storage^Test mobile apps^Optimize performance^Deploy to app stores",
                            Name = "React Native Mobile Development",
                            PL = 4,
                            Price = 230,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Master MongoDB in microservices architecture and distributed systems. Learn to design scalable database architectures for microservices. Understand data partitioning and sharding strategies. Implement event sourcing and CQRS patterns with MongoDB. Master distributed transactions and consistency patterns. Learn monitoring and optimization in distributed databases. Understand disaster recovery in distributed systems. Deploy and manage distributed MongoDB clusters.",
                            Img = "/images/v-2.png",
                            Learn = "Design microservices databases^Implement sharding^Handle distributed data^Manage transactions^Monitor performance^Scale databases^Implement security^Deploy clusters",
                            Name = "MongoDB for Microservices",
                            PL = 7,
                            Price = 260,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Create engaging browser-based games using HTML5 and Canvas. Master game loop implementation and animation techniques. Learn sprite manipulation and character animation. Implement collision detection and physics systems. Create engaging game mechanics and user interactions. Master sound integration and effects in HTML5 games. Learn game state management and save systems. Deploy and optimize HTML5 games for web browsers.",
                            Img = "/images/v-3.png",
                            Learn = "Create HTML5 games^Implement game loops^Handle animations^Add game physics^Manage game state^Integrate sound^Optimize performance^Deploy web games",
                            Name = "HTML5 Game Development",
                            PL = 1,
                            Price = 180,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Master mobile web application development with jQuery Mobile. Learn to create responsive and touch-friendly mobile interfaces. Understand mobile-specific event handling and gestures. Implement mobile-optimized forms and validation. Master mobile navigation patterns and transitions. Learn offline capabilities and local storage. Understand mobile performance optimization techniques. Deploy and manage mobile web applications.",
                            Img = "/images/v-4.jpg",
                            Learn = "Build mobile web apps^Handle touch events^Create mobile UIs^Implement navigation^Manage offline data^Optimize for mobile^Test applications^Deploy mobile apps",
                            Name = "jQuery Mobile App Development",
                            PL = 2,
                            Price = 190,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Master enterprise-level development with Bootstrap framework. Learn to create complex enterprise UI components and systems. Understand large-scale CSS architecture with Bootstrap. Implement enterprise-grade responsive design patterns. Master theme customization for corporate branding. Learn component library development with Bootstrap. Understand accessibility compliance in enterprise systems. Deploy and maintain large-scale Bootstrap applications.",
                            Img = "/images/v-5.jpg",
                            Learn = "Build enterprise UIs^Create component libraries^Implement design systems^Customize themes^Ensure accessibility^Manage large projects^Optimize performance^Deploy enterprise apps",
                            Name = "Enterprise Bootstrap Development",
                            PL = 0,
                            Price = 220,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Master advanced web development patterns and best practices. Learn modern features and functional programming concepts.",
                            Img = "/images/v-1.png",
                            Learn = "Master design patterns^Use modern features^Implement functional programming^Build scalable applications^Optimize performance^Write clean code^Test web apps^Deploy modern web apps",
                            Name = "Advanced Web Development",
                            PL = 1,
                            Price = 180,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Create cross-platform mobile applications using React Native framework. Build native iOS and Android apps with JavaScript.",
                            Img = "/images/v-2.png",
                            Learn = "Build mobile apps^Use native components^Handle device features^Create custom UI^Implement navigation^Manage state^Deploy to stores^Debug applications",
                            Name = "React Native Mobile Development",
                            PL = 4,
                            Price = 220,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Learn cloud computing fundamentals and advanced concepts using Amazon Web Services (AWS).",
                            Img = "/images/v-3.png",
                            Learn = "Setup AWS services^Deploy applications^Manage databases^Configure security^Scale services^Monitor performance^Implement DevOps^Optimize costs",
                            Name = "Cloud Computing with AWS",
                            PL = 6,
                            Price = 250,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Deep dive into machine learning using TensorFlow framework. Build and deploy AI models.",
                            Img = "/images/v-4.png",
                            Learn = "Build AI models^Train networks^Process data^Implement CNN^Use transfer learning^Deploy models^Optimize performance^Create AI apps",
                            Name = "Machine Learning with TensorFlow",
                            PL = 6,
                            Price = 280,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Master Vue.js 3 framework with Composition API and modern best practices.",
                            Img = "/images/v-5.jpg",
                            Learn = "Use Composition API^Build components^Manage state^Handle routing^Implement Vuex^Test applications^Deploy apps^Optimize performance",
                            Name = "Vue.js 3 Complete Guide",
                            PL = 4,
                            Price = 190,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Build enterprise-grade applications with Angular framework and TypeScript.",
                            Img = "/images/v-6.jpg",
                            Learn = "Master Angular^Use TypeScript^Create components^Manage state^Handle routing^Test apps^Deploy applications^Optimize performance",
                            Name = "Angular Enterprise Development",
                            PL = 5,
                            Price = 230,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Learn modern DevOps practices and implement continuous integration/deployment pipelines.",
                            Img = "/images/v-7.jpg",
                            Learn = "Setup CI/CD^Use Docker^Implement Kubernetes^Automate deployment^Monitor systems^Manage configs^Ensure security^Scale applications",
                            Name = "DevOps and CI/CD",
                            PL = 6,
                            Price = 260,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Learn modern web development with latest technologies and frameworks.",
                            Img = "/images/v-1.png",
                            Learn = "Create web apps^Use modern frameworks^Build responsive sites^Handle interactions^Implement security^Test websites^Deploy to cloud^Optimize performance",
                            Name = "Modern Web Development",
                            PL = 1,
                            Price = 270,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Create enterprise applications using Java and Spring framework.",
                            Img = "/images/v-2.png",
                            Learn = "Use Spring^Build APIs^Handle data^Implement security^Use Hibernate^Create services^Deploy apps^Debug systems",
                            Name = "Advanced Java Development",
                            PL = 5,
                            Price = 240,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Master database development with MongoDB and modern architecture components.",
                            Img = "/images/v-3.png",
                            Learn = "Use MongoDB^Build schemas^Handle data^Implement queries^Use aggregation^Create indexes^Deploy databases^Debug systems",
                            Name = "Database Development",
                            PL = 7,
                            Price = 230,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Create 2D and 3D games using modern game engines.",
                            Img = "/images/v-4.png",
                            Learn = "Use game engines^Create gameplay^Handle physics^Implement AI^Create animations^Add sound^Deploy games^Optimize performance",
                            Name = "Game Development Basics",
                            PL = 5,
                            Price = 250,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Learn data engineering principles and build robust data pipelines.",
                            Img = "/images/v-5.jpg",
                            Learn = "Build pipelines^Process data^Use databases^Handle big data^Implement ETL^Monitor systems^Ensure quality^Optimize performance",
                            Name = "Data Engineering",
                            PL = 6,
                            Price = 280,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Master cybersecurity principles and protect systems from threats.",
                            Img = "/images/v-6.jpg",
                            Learn = "Implement security^Handle threats^Use encryption^Protect systems^Monitor networks^Respond to incidents^Ensure compliance^Use best practices",
                            Name = "Cybersecurity Fundamentals",
                            PL = 6,
                            Price = 260,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Learn user interface and user experience design principles.",
                            Img = "/images/v-7.jpg",
                            Learn = "Design interfaces^Create wireframes^Build prototypes^Test usability^Handle feedback^Implement designs^Use design tools^Follow principles",
                            Name = "UI/UX Design",
                            PL = 1,
                            Price = 190,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Become a full stack developer with modern web technologies.",
                            Img = "/images/v-1.png",
                            Learn = "Build frontend^Create backend^Handle database^Implement security^Deploy apps^Monitor systems^Scale applications^Use best practices",
                            Name = "Full Stack Development",
                            PL = 5,
                            Price = 300,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Master database administration and optimization techniques.",
                            Img = "/images/v-2.png",
                            Learn = "Manage databases^Optimize queries^Ensure security^Handle backup^Monitor performance^Implement HA^Use best practices^Solve problems",
                            Name = "Database Administration",
                            PL = 7,
                            Price = 240,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Learn software architecture patterns and best practices.",
                            Img = "/images/v-3.png",
                            Learn = "Design systems^Use patterns^Handle scaling^Ensure security^Monitor performance^Make decisions^Document architecture^Lead teams",
                            Name = "Software Architecture",
                            PL = 5,
                            Price = 270,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Build cloud-native applications using modern technologies.",
                            Img = "/images/v-4.png",
                            Learn = "Use containers^Implement microservices^Handle scaling^Ensure resilience^Monitor systems^Deploy apps^Optimize performance^Follow practices",
                            Name = "Cloud Native Development",
                            PL = 5,
                            Price = 280,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Master natural language processing with Python and modern libraries.",
                            Img = "/images/v-5.jpg",
                            Learn = "Process text^Build models^Handle languages^Implement AI^Use NLTK^Create applications^Deploy solutions^Optimize performance",
                            Name = "Natural Language Processing",
                            PL = 6,
                            Price = 290,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Learn techniques to optimize web application performance.",
                            Img = "/images/v-6.jpg",
                            Learn = "Optimize loading^Handle caching^Improve rendering^Reduce size^Monitor performance^Debug issues^Use best practices^Implement PWA",
                            Name = "Web Performance",
                            PL = 1,
                            Price = 210,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Design and implement microservices-based applications.",
                            Img = "/images/v-7.jpg",
                            Learn = "Design services^Handle communication^Ensure security^Monitor systems^Scale apps^Deploy services^Handle failures^Use best practices",
                            Name = "Microservices Architecture",
                            PL = 5,
                            Price = 260,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Master frontend development and optimization techniques.",
                            Img = "/images/v-1.png",
                            Learn = "Build interfaces^Improve CSS^Handle assets^Use frameworks^Monitor performance^Debug issues^Implement PWA^Follow best practices",
                            Name = "Frontend Development",
                            PL = 1,
                            Price = 220,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Learn backend development with modern technologies.",
                            Img = "/images/v-2.png",
                            Learn = "Build APIs^Handle data^Ensure security^Monitor systems^Scale services^Deploy apps^Use best practices^Solve problems",
                            Name = "Backend Development",
                            PL = 5,
                            Price = 250,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Create beautiful and responsive mobile user interfaces.",
                            Img = "/images/v-3.png",
                            Learn = "Design UI^Handle responsive^Create animations^Implement UX^Use components^Test interfaces^Deploy apps^Follow principles",
                            Name = "Mobile UI Development",
                            PL = 4,
                            Price = 230,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Master software testing and quality assurance practices.",
                            Img = "/images/v-4.png",
                            Learn = "Write tests^Automate testing^Ensure quality^Handle CI/CD^Monitor systems^Debug issues^Use best practices^Improve processes",
                            Name = "Testing and Quality Assurance",
                            PL = 5,
                            Price = 240,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Learn to design and develop robust APIs.",
                            Img = "/images/v-5.jpg",
                            Learn = "Design APIs^Handle security^Document endpoints^Test APIs^Monitor usage^Scale services^Use best practices^Solve problems",
                            Name = "API Development",
                            PL = 5,
                            Price = 230,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 42,
                            Description = "Build modern progressive web applications.",
                            Img = "/images/v-6.jpg",
                            Learn = "Create PWAs^Handle offline^Use service workers^Implement push^Optimize performance^Deploy apps^Follow standards^Improve UX",
                            Name = "Web Applications",
                            PL = 1,
                            Price = 220,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 43,
                            Description = "Master data visualization techniques and tools.",
                            Img = "/images/v-7.jpg",
                            Learn = "Create charts^Handle data^Use libraries^Build dashboards^Implement interactivity^Deploy solutions^Follow principles^Improve UX",
                            Name = "Data Visualization",
                            PL = 6,
                            Price = 240,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 44,
                            Description = "Learn to build applications using cloud architecture.",
                            Img = "/images/v-1.png",
                            Learn = "Use cloud services^Handle events^Manage state^Monitor functions^Optimize costs^Deploy apps^Follow practices^Solve problems",
                            Name = "Cloud Architecture",
                            PL = 5,
                            Price = 260,
                            Video = "/images/video4.mp4"
                        },
                        new
                        {
                            Id = 45,
                            Description = "Build cross-platform applications using modern frameworks.",
                            Img = "/images/v-2.png",
                            Learn = "Use frameworks^Share code^Handle platform^Create UI^Implement features^Deploy apps^Follow practices^Solve problems",
                            Name = "Cross-Platform Development",
                            PL = 4,
                            Price = 250,
                            Video = "/images/video4.mp4"
                        });
                });

            modelBuilder.Entity("Elomoas.Domain.Entities.CourseSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationInMonths")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SubscriptionPrice")
                        .HasColumnType("numeric");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseSubscriptions");
                });

            modelBuilder.Entity("Elomoas.Domain.Entities.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FriendId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Elomoas.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Img")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("PL")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Learn new secrets to creating awesome Microsoft Access databases and VBA coding not covered in any of my other courses!",
                            Img = "/images/download1.png",
                            Name = "Mobile Product Design",
                            PL = 5
                        },
                        new
                        {
                            Id = 2,
                            Description = "Learn new secrets to creating awesome Microsoft Access databases and VBA coding not covered in any of my other courses!",
                            Img = "/images/download2.png",
                            Name = "HTML Developer",
                            PL = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Learn new secrets to creating awesome Microsoft Access databases and VBA coding not covered in any of my other courses!",
                            Img = "/images/download4.png",
                            Name = "Advanced CSS and Sass",
                            PL = 0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Learn new secrets to creating awesome Microsoft Access databases and VBA coding not covered in any of my other courses!",
                            Img = "/images/download5.png",
                            Name = "Modern React with Redux",
                            PL = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Learn new secrets to creating awesome Microsoft Access databases and VBA coding not covered in any of my other courses!",
                            Img = "/images/download6.png",
                            Name = "Node JS",
                            PL = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Master Python programming with advanced concepts and real-world applications!",
                            Img = "/images/download7.png",
                            Name = "Advanced Python Development",
                            PL = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Become a full-stack developer with modern JavaScript frameworks and tools!",
                            Img = "/images/download1.png",
                            Name = "Full Stack JavaScript",
                            PL = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Learn Vue.js from basics to advanced concepts with practical projects!",
                            Img = "/images/download2.png",
                            Name = "Vue.js Mastery",
                            PL = 4
                        },
                        new
                        {
                            Id = 9,
                            Description = "Build enterprise-level applications with Angular framework!",
                            Img = "/images/download3.png",
                            Name = "Angular Enterprise",
                            PL = 5
                        },
                        new
                        {
                            Id = 10,
                            Description = "Master DevOps practices and tools for modern software development!",
                            Img = "/images/download4.png",
                            Name = "DevOps Essentials",
                            PL = 6
                        },
                        new
                        {
                            Id = 11,
                            Description = "Design and implement scalable cloud solutions!",
                            Img = "/images/download5.png",
                            Name = "Cloud Architecture",
                            PL = 5
                        },
                        new
                        {
                            Id = 12,
                            Description = "Create cross-platform mobile applications with modern frameworks!",
                            Img = "/images/download6.png",
                            Name = "Mobile App Development",
                            PL = 4
                        },
                        new
                        {
                            Id = 13,
                            Description = "Learn the basics of data science and machine learning!",
                            Img = "/images/download7.png",
                            Name = "Data Science Fundamentals",
                            PL = 6
                        },
                        new
                        {
                            Id = 14,
                            Description = "Master web security concepts and best practices!",
                            Img = "/images/download1.png",
                            Name = "Web Security",
                            PL = 5
                        },
                        new
                        {
                            Id = 15,
                            Description = "Create beautiful and user-friendly interfaces!",
                            Img = "/images/download2.png",
                            Name = "UI/UX Design",
                            PL = 1
                        },
                        new
                        {
                            Id = 16,
                            Description = "Learn frontend development with modern frameworks!",
                            Img = "/images/download3.png",
                            Name = "Frontend Development",
                            PL = 4
                        },
                        new
                        {
                            Id = 17,
                            Description = "Create exciting games with modern game development frameworks!",
                            Img = "/images/download4.png",
                            Name = "Game Development",
                            PL = 5
                        },
                        new
                        {
                            Id = 18,
                            Description = "Deep dive into machine learning algorithms and applications!",
                            Img = "/images/download5.png",
                            Name = "Machine Learning",
                            PL = 6
                        },
                        new
                        {
                            Id = 19,
                            Description = "Master database design and optimization techniques!",
                            Img = "/images/download6.png",
                            Name = "Database Design",
                            PL = 7
                        },
                        new
                        {
                            Id = 20,
                            Description = "Learn to design and implement scalable software architectures!",
                            Img = "/images/download7.png",
                            Name = "Software Architecture",
                            PL = 5
                        });
                });

            modelBuilder.Entity("Elomoas.Domain.Entities.GroupSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupSubscriptions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Elomoas.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("Elomoas.Domain.Entities.AppUser", "IdentityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Elomoas.Domain.Entities.CourseSubscription", b =>
                {
                    b.HasOne("Elomoas.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elomoas.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Elomoas.Domain.Entities.GroupSubscription", b =>
                {
                    b.HasOne("Elomoas.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Elomoas.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
